version: 1.0.{build}

environment:
  matrix:
  - Configuration: Release
  - Configuration: Debug

before_build:
  - nuget restore
  - appveyor DownloadFile https://raw.githubusercontent.com/dbolkensteyn/pr-analysis/ondemand/msbuild-sonarqube-runner-begin.cmd && msbuild-sonarqube-runner-begin

build:
  verbosity: minimal
  project: SonarQube.MSBuild.Runner.sln
  
after_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/dbolkensteyn/pr-analysis/ondemand/msbuild-sonarqube-runner-end.cmd && msbuild-sonarqube-runner-end

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
